---
abstract: 'Override Request Content Body by File Uploading or Query Parameter'
author:
  - 'Yusuke Kawasaki'
build_requires:
  HTTP::Request: 0
  Plack::Test: 0
  Test::More: 0
  URI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.55
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ContentOverride
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  IO::File: 0
  Plack: 0.9948
version: 0.01
